### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by mtucker502** [testdrivenio/fastapi-sqlmodel-alembic#13]
Thanks Mike, appreciate the help this repo provided.

One question though: Where are the tests? Isn't this test-driven.io 😂

I read another article you posted (https://testdriven.io/blog/fastapi-crud/) and noticed you use monkey patching to make the tests pass. Is there no way to use pytest + async db/routes without monkeypatching?

**Comment by mjhea0** [comment]
Yes, check out the [Test-Driven Development with FastAPI and Docker](https://testdriven.io/courses/tdd-fastapi/) course. You can see the code here: https://github.com/testdrivenio/fastapi-tdd-docker
