### ISSUE TITLE
init_db() not called during startup?

### ISSUE THREAD

**Issue by sidmitra** [testdrivenio/fastapi-sqlmodel-alembic#7]
I noticed that in the [article](https://testdriven.io/blog/fastapi-sqlmodel/) init_db was being called in [main.py ](https://github.com/testdrivenio/fastapi-sqlmodel-alembic/blob/main/project/app/main.py)but in the current version that's not happening. I combed through all the files figuring out if i missed it somewhere. Is there a reason or was just missed?  

```python
@app.on_event("startup")
async def on_startup():
    await init_db()
```

**Comment by mtucker502** [comment]
Isn't init_db() removed in favor of using alembic?
